<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\CommerceFlow.Legacy.Models\CommerceFlow.Legacy.Models.csproj" />
    <ProjectReference Include="..\CommerceFlow.Legacy.DAL\CommerceFlow.Legacy.DAL.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
